sudo: required

language: generic
services:
  - docker

before_install:
  - docker build -t cash76/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true cash76/docker-react npm run test